//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.19 at 11:59:33 PM EDT 
//


package org.opendaylight.iotdm.primitive;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for accessControlRule complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="accessControlRule">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="acor" type="{http://www.onem2m.org/xml/protocols}listOfURIs"/>
 *         &lt;element name="acop" type="{http://www.onem2m.org/xml/protocols}accessControlOperations"/>
 *         &lt;element name="acco" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="actw" type="{http://www.onem2m.org/xml/protocols}scheduleEntry" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="acip" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ipv4" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction>
 *                                   &lt;simpleType>
 *                                     &lt;list itemType="{http://www.onem2m.org/xml/protocols}ipv4" />
 *                                   &lt;/simpleType>
 *                                   &lt;minLength value="1"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="ipv6" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction>
 *                                   &lt;simpleType>
 *                                     &lt;list itemType="{http://www.onem2m.org/xml/protocols}ipv6" />
 *                                   &lt;/simpleType>
 *                                   &lt;minLength value="1"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="aclr" type="{http://www.onem2m.org/xml/protocols}locationRegion" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "accessControlRule", propOrder = {
    "acor",
    "acop",
    "acco"
})
public class AccessControlRule {

    @XmlList
    @XmlElement(required = true)
    protected List<String> acor;
    @XmlElement(required = true)
    protected BigInteger acop;
    protected List<AccessControlRule.Acco> acco;

    /**
     * Gets the value of the acor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the acor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAcor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAcor() {
        if (acor == null) {
            acor = new ArrayList<String>();
        }
        return this.acor;
    }

    /**
     * Gets the value of the acop property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAcop() {
        return acop;
    }

    /**
     * Sets the value of the acop property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAcop(BigInteger value) {
        this.acop = value;
    }

    /**
     * Gets the value of the acco property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the acco property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAcco().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AccessControlRule.Acco }
     * 
     * 
     */
    public List<AccessControlRule.Acco> getAcco() {
        if (acco == null) {
            acco = new ArrayList<AccessControlRule.Acco>();
        }
        return this.acco;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="actw" type="{http://www.onem2m.org/xml/protocols}scheduleEntry" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="acip" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ipv4" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction>
     *                         &lt;simpleType>
     *                           &lt;list itemType="{http://www.onem2m.org/xml/protocols}ipv4" />
     *                         &lt;/simpleType>
     *                         &lt;minLength value="1"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="ipv6" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction>
     *                         &lt;simpleType>
     *                           &lt;list itemType="{http://www.onem2m.org/xml/protocols}ipv6" />
     *                         &lt;/simpleType>
     *                         &lt;minLength value="1"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="aclr" type="{http://www.onem2m.org/xml/protocols}locationRegion" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "actw",
        "acip",
        "aclr"
    })
    public static class Acco {

        protected List<String> actw;
        protected AccessControlRule.Acco.Acip acip;
        protected LocationRegion aclr;

        /**
         * Gets the value of the actw property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the actw property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getActw().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getActw() {
            if (actw == null) {
                actw = new ArrayList<String>();
            }
            return this.actw;
        }

        /**
         * Gets the value of the acip property.
         * 
         * @return
         *     possible object is
         *     {@link AccessControlRule.Acco.Acip }
         *     
         */
        public AccessControlRule.Acco.Acip getAcip() {
            return acip;
        }

        /**
         * Sets the value of the acip property.
         * 
         * @param value
         *     allowed object is
         *     {@link AccessControlRule.Acco.Acip }
         *     
         */
        public void setAcip(AccessControlRule.Acco.Acip value) {
            this.acip = value;
        }

        /**
         * Gets the value of the aclr property.
         * 
         * @return
         *     possible object is
         *     {@link LocationRegion }
         *     
         */
        public LocationRegion getAclr() {
            return aclr;
        }

        /**
         * Sets the value of the aclr property.
         * 
         * @param value
         *     allowed object is
         *     {@link LocationRegion }
         *     
         */
        public void setAclr(LocationRegion value) {
            this.aclr = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ipv4" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction>
         *               &lt;simpleType>
         *                 &lt;list itemType="{http://www.onem2m.org/xml/protocols}ipv4" />
         *               &lt;/simpleType>
         *               &lt;minLength value="1"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="ipv6" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction>
         *               &lt;simpleType>
         *                 &lt;list itemType="{http://www.onem2m.org/xml/protocols}ipv6" />
         *               &lt;/simpleType>
         *               &lt;minLength value="1"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "ipv4",
            "ipv6"
        })
        public static class Acip {

            @XmlList
            protected List<String> ipv4;
            @XmlList
            protected List<String> ipv6;

            /**
             * Gets the value of the ipv4 property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the ipv4 property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getIpv4().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getIpv4() {
                if (ipv4 == null) {
                    ipv4 = new ArrayList<String>();
                }
                return this.ipv4;
            }

            /**
             * Gets the value of the ipv6 property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the ipv6 property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getIpv6().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getIpv6() {
                if (ipv6 == null) {
                    ipv6 = new ArrayList<String>();
                }
                return this.ipv6;
            }

        }

    }

}
