//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.19 at 11:59:33 PM EDT 
//


package org.opendaylight.iotdm.primitive;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.onem2m.org/xml/protocols}announcedResource">
 *       &lt;sequence>
 *         &lt;element name="apn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="api" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="aei" type="{http://www.onem2m.org/xml/protocols}ID"/>
 *         &lt;element name="poa" type="{http://www.onem2m.org/xml/protocols}poaList" minOccurs="0"/>
 *         &lt;element name="or" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="nl" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="rr" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="ch" type="{http://www.onem2m.org/xml/protocols}childResourceRef" maxOccurs="unbounded"/>
 *           &lt;choice maxOccurs="unbounded">
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}cnt"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}cntA"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}grp"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}grpA"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}acp"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}acpA"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}sub"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}schA"/>
 *           &lt;/choice>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "apn",
    "api",
    "aei",
    "poa",
    "or",
    "nl",
    "rr",
    "ch",
    "cntOrCntAOrGrp"
})
@XmlRootElement(name = "aeA")
public class AeA
    extends AnnouncedResource
{

    protected String apn;
    @XmlElement(required = true)
    protected String api;
    @XmlElement(required = true)
    protected String aei;
    @XmlList
    protected List<String> poa;
    @XmlSchemaType(name = "anyURI")
    protected String or;
    @XmlSchemaType(name = "anyURI")
    protected String nl;
    protected Boolean rr;
    protected List<ChildResourceRef> ch;
    @XmlElements({
        @XmlElement(name = "cnt", namespace = "http://www.onem2m.org/xml/protocols", type = Cnt.class),
        @XmlElement(name = "cntA", namespace = "http://www.onem2m.org/xml/protocols", type = CntA.class),
        @XmlElement(name = "grp", namespace = "http://www.onem2m.org/xml/protocols", type = Grp.class),
        @XmlElement(name = "grpA", namespace = "http://www.onem2m.org/xml/protocols", type = GrpA.class),
        @XmlElement(name = "acp", namespace = "http://www.onem2m.org/xml/protocols", type = Acp.class),
        @XmlElement(name = "acpA", namespace = "http://www.onem2m.org/xml/protocols", type = AcpA.class),
        @XmlElement(name = "sub", namespace = "http://www.onem2m.org/xml/protocols", type = Sub.class),
        @XmlElement(name = "schA", namespace = "http://www.onem2m.org/xml/protocols", type = SchA.class)
    })
    protected List<Resource> cntOrCntAOrGrp;

    /**
     * Gets the value of the apn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApn() {
        return apn;
    }

    /**
     * Sets the value of the apn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApn(String value) {
        this.apn = value;
    }

    /**
     * Gets the value of the api property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApi() {
        return api;
    }

    /**
     * Sets the value of the api property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApi(String value) {
        this.api = value;
    }

    /**
     * Gets the value of the aei property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAei() {
        return aei;
    }

    /**
     * Sets the value of the aei property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAei(String value) {
        this.aei = value;
    }

    /**
     * Gets the value of the poa property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the poa property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPoa().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPoa() {
        if (poa == null) {
            poa = new ArrayList<String>();
        }
        return this.poa;
    }

    /**
     * Gets the value of the or property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOr() {
        return or;
    }

    /**
     * Sets the value of the or property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOr(String value) {
        this.or = value;
    }

    /**
     * Gets the value of the nl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNl() {
        return nl;
    }

    /**
     * Sets the value of the nl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNl(String value) {
        this.nl = value;
    }

    /**
     * Gets the value of the rr property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRr() {
        return rr;
    }

    /**
     * Sets the value of the rr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRr(Boolean value) {
        this.rr = value;
    }

    /**
     * Gets the value of the ch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCh().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ChildResourceRef }
     * 
     * 
     */
    public List<ChildResourceRef> getCh() {
        if (ch == null) {
            ch = new ArrayList<ChildResourceRef>();
        }
        return this.ch;
    }

    /**
     * Gets the value of the cntOrCntAOrGrp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cntOrCntAOrGrp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCntOrCntAOrGrp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Cnt }
     * {@link CntA }
     * {@link Grp }
     * {@link GrpA }
     * {@link Acp }
     * {@link AcpA }
     * {@link Sub }
     * {@link SchA }
     * 
     * 
     */
    public List<Resource> getCntOrCntAOrGrp() {
        if (cntOrCntAOrGrp == null) {
            cntOrCntAOrGrp = new ArrayList<Resource>();
        }
        return this.cntOrCntAOrGrp;
    }

}
