//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.21 at 02:34:26 PM EDT 
//


package org.opendaylight.iotdm.primitive;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.onem2m.org/xml/protocols}mgmtResource">
 *       &lt;sequence>
 *         &lt;element name="cpn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cmlk" type="{http://www.onem2m.org/xml/protocols}mgmtLinkRef" maxOccurs="unbounded" minOccurs="4"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cpn",
    "cmlk"
})
@XmlRootElement(name = "cmp")
public class Cmp
    extends MgmtResource
{

    @XmlElement(required = true)
    protected String cpn;
    @XmlElement(required = true)
    protected List<MgmtLinkRef> cmlk;

    /**
     * Gets the value of the cpn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCpn() {
        return cpn;
    }

    /**
     * Sets the value of the cpn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCpn(String value) {
        this.cpn = value;
    }

    /**
     * Gets the value of the cmlk property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cmlk property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCmlk().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MgmtLinkRef }
     * 
     * 
     */
    public List<MgmtLinkRef> getCmlk() {
        if (cmlk == null) {
            cmlk = new ArrayList<MgmtLinkRef>();
        }
        return this.cmlk;
    }

}
