//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.19 at 11:59:33 PM EDT 
//


package org.opendaylight.iotdm.primitive;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.onem2m.org/xml/protocols}announceableResource">
 *       &lt;sequence>
 *         &lt;element name="cst" type="{http://www.onem2m.org/xml/protocols}cseTypeID" minOccurs="0"/>
 *         &lt;element name="poa" type="{http://www.onem2m.org/xml/protocols}poaList" minOccurs="0"/>
 *         &lt;element name="cb" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="csi" type="{http://www.onem2m.org/xml/protocols}ID"/>
 *         &lt;element name="mei" type="{http://www.onem2m.org/xml/protocols}externalID" minOccurs="0"/>
 *         &lt;element name="tri" type="{http://www.onem2m.org/xml/protocols}triggerRecipientID" minOccurs="0"/>
 *         &lt;element name="rr" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="nl" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="ch" type="{http://www.onem2m.org/xml/protocols}childResourceRef" maxOccurs="unbounded"/>
 *           &lt;choice maxOccurs="unbounded">
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}cnt"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}grp"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}acp"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}sub"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}pch"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}sch"/>
 *           &lt;/choice>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cst",
    "poa",
    "cb",
    "csi",
    "mei",
    "tri",
    "rr",
    "nl",
    "ch",
    "cntOrGrpOrAcp"
})
@XmlRootElement(name = "csr")
public class Csr
    extends AnnounceableResource
{

    protected BigInteger cst;
    @XmlList
    protected List<String> poa;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String cb;
    @XmlElement(required = true)
    protected String csi;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String mei;
    protected Long tri;
    protected boolean rr;
    @XmlSchemaType(name = "anyURI")
    protected String nl;
    protected List<ChildResourceRef> ch;
    @XmlElements({
        @XmlElement(name = "cnt", namespace = "http://www.onem2m.org/xml/protocols", type = Cnt.class),
        @XmlElement(name = "grp", namespace = "http://www.onem2m.org/xml/protocols", type = Grp.class),
        @XmlElement(name = "acp", namespace = "http://www.onem2m.org/xml/protocols", type = Acp.class),
        @XmlElement(name = "sub", namespace = "http://www.onem2m.org/xml/protocols", type = Sub.class),
        @XmlElement(name = "pch", namespace = "http://www.onem2m.org/xml/protocols", type = Pch.class),
        @XmlElement(name = "sch", namespace = "http://www.onem2m.org/xml/protocols", type = Sch.class)
    })
    protected List<Resource> cntOrGrpOrAcp;

    /**
     * Gets the value of the cst property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCst() {
        return cst;
    }

    /**
     * Sets the value of the cst property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCst(BigInteger value) {
        this.cst = value;
    }

    /**
     * Gets the value of the poa property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the poa property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPoa().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPoa() {
        if (poa == null) {
            poa = new ArrayList<String>();
        }
        return this.poa;
    }

    /**
     * Gets the value of the cb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCb() {
        return cb;
    }

    /**
     * Sets the value of the cb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCb(String value) {
        this.cb = value;
    }

    /**
     * Gets the value of the csi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCsi() {
        return csi;
    }

    /**
     * Sets the value of the csi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCsi(String value) {
        this.csi = value;
    }

    /**
     * Gets the value of the mei property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMei() {
        return mei;
    }

    /**
     * Sets the value of the mei property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMei(String value) {
        this.mei = value;
    }

    /**
     * Gets the value of the tri property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTri() {
        return tri;
    }

    /**
     * Sets the value of the tri property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTri(Long value) {
        this.tri = value;
    }

    /**
     * Gets the value of the rr property.
     * 
     */
    public boolean isRr() {
        return rr;
    }

    /**
     * Sets the value of the rr property.
     * 
     */
    public void setRr(boolean value) {
        this.rr = value;
    }

    /**
     * Gets the value of the nl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNl() {
        return nl;
    }

    /**
     * Sets the value of the nl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNl(String value) {
        this.nl = value;
    }

    /**
     * Gets the value of the ch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCh().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ChildResourceRef }
     * 
     * 
     */
    public List<ChildResourceRef> getCh() {
        if (ch == null) {
            ch = new ArrayList<ChildResourceRef>();
        }
        return this.ch;
    }

    /**
     * Gets the value of the cntOrGrpOrAcp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cntOrGrpOrAcp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCntOrGrpOrAcp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Cnt }
     * {@link Grp }
     * {@link Acp }
     * {@link Sub }
     * {@link Pch }
     * {@link Sch }
     * 
     * 
     */
    public List<Resource> getCntOrGrpOrAcp() {
        if (cntOrGrpOrAcp == null) {
            cntOrGrpOrAcp = new ArrayList<Resource>();
        }
        return this.cntOrGrpOrAcp;
    }

}
