//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.19 at 11:59:33 PM EDT 
//


package org.opendaylight.iotdm.primitive;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.Duration;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.onem2m.org/xml/protocols}regularResource">
 *       &lt;sequence>
 *         &lt;element name="dc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cmt" type="{http://www.onem2m.org/xml/protocols}cmdType"/>
 *         &lt;element name="exra" type="{http://www.onem2m.org/xml/protocols}execReqArgsListType" minOccurs="0"/>
 *         &lt;element name="exe" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="ext" type="{http://www.onem2m.org/xml/protocols}nodeID"/>
 *         &lt;element name="exm" type="{http://www.onem2m.org/xml/protocols}execModeType" minOccurs="0"/>
 *         &lt;element name="exf" type="{http://www.w3.org/2001/XMLSchema}duration" minOccurs="0"/>
 *         &lt;element name="exy" type="{http://www.w3.org/2001/XMLSchema}duration" minOccurs="0"/>
 *         &lt;element name="exn" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="ch" type="{http://www.onem2m.org/xml/protocols}childResourceRef" maxOccurs="unbounded"/>
 *           &lt;choice maxOccurs="unbounded">
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}exin"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}sub"/>
 *           &lt;/choice>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dc",
    "cmt",
    "exra",
    "exe",
    "ext",
    "exm",
    "exf",
    "exy",
    "exn",
    "ch",
    "exinOrSub"
})
@XmlRootElement(name = "mgc")
public class Mgc
    extends RegularResource
{

    protected String dc;
    @XmlElement(required = true)
    protected BigInteger cmt;
    protected ExecReqArgsListType exra;
    protected boolean exe;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String ext;
    protected BigInteger exm;
    protected Duration exf;
    protected Duration exy;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger exn;
    protected List<ChildResourceRef> ch;
    @XmlElements({
        @XmlElement(name = "exin", namespace = "http://www.onem2m.org/xml/protocols", type = Exin.class),
        @XmlElement(name = "sub", namespace = "http://www.onem2m.org/xml/protocols", type = Sub.class)
    })
    protected List<RegularResource> exinOrSub;

    /**
     * Gets the value of the dc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDc() {
        return dc;
    }

    /**
     * Sets the value of the dc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDc(String value) {
        this.dc = value;
    }

    /**
     * Gets the value of the cmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCmt() {
        return cmt;
    }

    /**
     * Sets the value of the cmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCmt(BigInteger value) {
        this.cmt = value;
    }

    /**
     * Gets the value of the exra property.
     * 
     * @return
     *     possible object is
     *     {@link ExecReqArgsListType }
     *     
     */
    public ExecReqArgsListType getExra() {
        return exra;
    }

    /**
     * Sets the value of the exra property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExecReqArgsListType }
     *     
     */
    public void setExra(ExecReqArgsListType value) {
        this.exra = value;
    }

    /**
     * Gets the value of the exe property.
     * 
     */
    public boolean isExe() {
        return exe;
    }

    /**
     * Sets the value of the exe property.
     * 
     */
    public void setExe(boolean value) {
        this.exe = value;
    }

    /**
     * Gets the value of the ext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExt() {
        return ext;
    }

    /**
     * Sets the value of the ext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExt(String value) {
        this.ext = value;
    }

    /**
     * Gets the value of the exm property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getExm() {
        return exm;
    }

    /**
     * Sets the value of the exm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setExm(BigInteger value) {
        this.exm = value;
    }

    /**
     * Gets the value of the exf property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getExf() {
        return exf;
    }

    /**
     * Sets the value of the exf property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setExf(Duration value) {
        this.exf = value;
    }

    /**
     * Gets the value of the exy property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getExy() {
        return exy;
    }

    /**
     * Sets the value of the exy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setExy(Duration value) {
        this.exy = value;
    }

    /**
     * Gets the value of the exn property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getExn() {
        return exn;
    }

    /**
     * Sets the value of the exn property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setExn(BigInteger value) {
        this.exn = value;
    }

    /**
     * Gets the value of the ch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCh().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ChildResourceRef }
     * 
     * 
     */
    public List<ChildResourceRef> getCh() {
        if (ch == null) {
            ch = new ArrayList<ChildResourceRef>();
        }
        return this.ch;
    }

    /**
     * Gets the value of the exinOrSub property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the exinOrSub property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExinOrSub().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Exin }
     * {@link Sub }
     * 
     * 
     */
    public List<RegularResource> getExinOrSub() {
        if (exinOrSub == null) {
            exinOrSub = new ArrayList<RegularResource>();
        }
        return this.exinOrSub;
    }

}
