//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.26 at 12:59:59 PM EDT 
//


package org.opendaylight.iotdm.primitive;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.onem2m.org/xml/protocols}announceableResource">
 *       &lt;sequence>
 *         &lt;element name="ni" type="{http://www.onem2m.org/xml/protocols}nodeID"/>
 *         &lt;element name="hcl" type="{http://www.onem2m.org/xml/protocols}ID" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="ch" type="{http://www.onem2m.org/xml/protocols}childResourceRef" maxOccurs="unbounded"/>
 *           &lt;choice maxOccurs="unbounded">
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}memA"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}batA"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}aniA"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}andiA"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}fwrA"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}swrA"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}dviA"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}dvcA"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}rboA"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}evlA"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}sub"/>
 *           &lt;/choice>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ni",
    "hcl",
    "ch",
    "memAOrBatAOrAniA"
})
@XmlRootElement(name = "nodA")
public class NodA
    extends AnnounceableResource
{

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String ni;
    protected String hcl;
    protected List<ChildResourceRef> ch;
    @XmlElements({
        @XmlElement(name = "memA", namespace = "http://www.onem2m.org/xml/protocols", type = MemA.class),
        @XmlElement(name = "batA", namespace = "http://www.onem2m.org/xml/protocols", type = BatA.class),
        @XmlElement(name = "aniA", namespace = "http://www.onem2m.org/xml/protocols", type = AniA.class),
        @XmlElement(name = "andiA", namespace = "http://www.onem2m.org/xml/protocols", type = AndiA.class),
        @XmlElement(name = "fwrA", namespace = "http://www.onem2m.org/xml/protocols", type = FwrA.class),
        @XmlElement(name = "swrA", namespace = "http://www.onem2m.org/xml/protocols", type = SwrA.class),
        @XmlElement(name = "dviA", namespace = "http://www.onem2m.org/xml/protocols", type = DviA.class),
        @XmlElement(name = "dvcA", namespace = "http://www.onem2m.org/xml/protocols", type = DvcA.class),
        @XmlElement(name = "rboA", namespace = "http://www.onem2m.org/xml/protocols", type = RboA.class),
        @XmlElement(name = "evlA", namespace = "http://www.onem2m.org/xml/protocols", type = EvlA.class),
        @XmlElement(name = "sub", namespace = "http://www.onem2m.org/xml/protocols", type = Sub.class)
    })
    protected List<Resource> memAOrBatAOrAniA;

    /**
     * Gets the value of the ni property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNi() {
        return ni;
    }

    /**
     * Sets the value of the ni property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNi(String value) {
        this.ni = value;
    }

    /**
     * Gets the value of the hcl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHcl() {
        return hcl;
    }

    /**
     * Sets the value of the hcl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHcl(String value) {
        this.hcl = value;
    }

    /**
     * Gets the value of the ch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCh().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ChildResourceRef }
     * 
     * 
     */
    public List<ChildResourceRef> getCh() {
        if (ch == null) {
            ch = new ArrayList<ChildResourceRef>();
        }
        return this.ch;
    }

    /**
     * Gets the value of the memAOrBatAOrAniA property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the memAOrBatAOrAniA property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMemAOrBatAOrAniA().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MemA }
     * {@link BatA }
     * {@link AniA }
     * {@link AndiA }
     * {@link FwrA }
     * {@link SwrA }
     * {@link DviA }
     * {@link DvcA }
     * {@link RboA }
     * {@link EvlA }
     * {@link Sub }
     * 
     * 
     */
    public List<Resource> getMemAOrBatAOrAniA() {
        if (memAOrBatAOrAniA == null) {
            memAOrBatAOrAniA = new ArrayList<Resource>();
        }
        return this.memAOrBatAOrAniA;
    }

}
