//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.24 at 05:38:13 PM EDT 
//


package org.opendaylight.iotdm.primitive;

import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.opendaylight.iotdm.primitive package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Sgn_QNAME = new QName("http://www.onem2m.org/xml/protocols", "sgn");
    private final static QName _Agn_QNAME = new QName("http://www.onem2m.org/xml/protocols", "agn");
    private final static QName _Agr_QNAME = new QName("http://www.onem2m.org/xml/protocols", "agr");
    private final static QName _Atrl_QNAME = new QName("http://www.onem2m.org/xml/protocols", "atrl");
    private final static QName _Uril_QNAME = new QName("http://www.onem2m.org/xml/protocols", "uril");
    private final static QName _Rce_QNAME = new QName("http://www.onem2m.org/xml/protocols", "rce");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.opendaylight.iotdm.primitive
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AccessControlRule }
     * 
     */
    public AccessControlRule createAccessControlRule() {
        return new AccessControlRule();
    }

    /**
     * Create an instance of {@link AccessControlRule.Acco }
     * 
     */
    public AccessControlRule.Acco createAccessControlRuleAcco() {
        return new AccessControlRule.Acco();
    }

    /**
     * Create an instance of {@link AggregatedRequest }
     * 
     */
    public AggregatedRequest createAggregatedRequest() {
        return new AggregatedRequest();
    }

    /**
     * Create an instance of {@link Notification }
     * 
     */
    public Notification createNotification() {
        return new Notification();
    }

    /**
     * Create an instance of {@link Notification.Nev }
     * 
     */
    public Notification.Nev createNotificationNev() {
        return new Notification.Nev();
    }

    /**
     * Create an instance of {@link Cmbf }
     * 
     */
    public Cmbf createCmbf() {
        return new Cmbf();
    }

    /**
     * Create an instance of {@link MgmtResource }
     * 
     */
    public MgmtResource createMgmtResource() {
        return new MgmtResource();
    }

    /**
     * Create an instance of {@link AnnounceableResource }
     * 
     */
    public AnnounceableResource createAnnounceableResource() {
        return new AnnounceableResource();
    }

    /**
     * Create an instance of {@link RegularResource }
     * 
     */
    public RegularResource createRegularResource() {
        return new RegularResource();
    }

    /**
     * Create an instance of {@link Resource }
     * 
     */
    public Resource createResource() {
        return new Resource();
    }

    /**
     * Create an instance of {@link Cmnr }
     * 
     */
    public Cmnr createCmnr() {
        return new Cmnr();
    }

    /**
     * Create an instance of {@link MgmtLinkRef }
     * 
     */
    public MgmtLinkRef createMgmtLinkRef() {
        return new MgmtLinkRef();
    }

    /**
     * Create an instance of {@link AttributeList }
     * 
     */
    public AttributeList createAttributeList() {
        return new AttributeList();
    }

    /**
     * Create an instance of {@link Csr }
     * 
     */
    public Csr createCsr() {
        return new Csr();
    }

    /**
     * Create an instance of {@link ChildResourceRef }
     * 
     */
    public ChildResourceRef createChildResourceRef() {
        return new ChildResourceRef();
    }

    /**
     * Create an instance of {@link Cnt }
     * 
     */
    public Cnt createCnt() {
        return new Cnt();
    }

    /**
     * Create an instance of {@link Cin }
     * 
     */
    public Cin createCin() {
        return new Cin();
    }

    /**
     * Create an instance of {@link AnnounceableSubordinateResource }
     * 
     */
    public AnnounceableSubordinateResource createAnnounceableSubordinateResource() {
        return new AnnounceableSubordinateResource();
    }

    /**
     * Create an instance of {@link Sub }
     * 
     */
    public Sub createSub() {
        return new Sub();
    }

    /**
     * Create an instance of {@link EventNotificationCriteria }
     * 
     */
    public EventNotificationCriteria createEventNotificationCriteria() {
        return new EventNotificationCriteria();
    }

    /**
     * Create an instance of {@link BatchNotify }
     * 
     */
    public BatchNotify createBatchNotify() {
        return new BatchNotify();
    }

    /**
     * Create an instance of {@link RateLimit }
     * 
     */
    public RateLimit createRateLimit() {
        return new RateLimit();
    }

    /**
     * Create an instance of {@link Sch }
     * 
     */
    public Sch createSch() {
        return new Sch();
    }

    /**
     * Create an instance of {@link ScheduleEntries }
     * 
     */
    public ScheduleEntries createScheduleEntries() {
        return new ScheduleEntries();
    }

    /**
     * Create an instance of {@link Grp }
     * 
     */
    public Grp createGrp() {
        return new Grp();
    }

    /**
     * Create an instance of {@link Acp }
     * 
     */
    public Acp createAcp() {
        return new Acp();
    }

    /**
     * Create an instance of {@link SetOfAcrs }
     * 
     */
    public SetOfAcrs createSetOfAcrs() {
        return new SetOfAcrs();
    }

    /**
     * Create an instance of {@link Pch }
     * 
     */
    public Pch createPch() {
        return new Pch();
    }

    /**
     * Create an instance of {@link AndiA }
     * 
     */
    public AndiA createAndiA() {
        return new AndiA();
    }

    /**
     * Create an instance of {@link AnnouncedMgmtResource }
     * 
     */
    public AnnouncedMgmtResource createAnnouncedMgmtResource() {
        return new AnnouncedMgmtResource();
    }

    /**
     * Create an instance of {@link AnnouncedResource }
     * 
     */
    public AnnouncedResource createAnnouncedResource() {
        return new AnnouncedResource();
    }

    /**
     * Create an instance of {@link Mgc }
     * 
     */
    public Mgc createMgc() {
        return new Mgc();
    }

    /**
     * Create an instance of {@link ExecReqArgsListType }
     * 
     */
    public ExecReqArgsListType createExecReqArgsListType() {
        return new ExecReqArgsListType();
    }

    /**
     * Create an instance of {@link Exin }
     * 
     */
    public Exin createExin() {
        return new Exin();
    }

    /**
     * Create an instance of {@link AggregatedNotification }
     * 
     */
    public AggregatedNotification createAggregatedNotification() {
        return new AggregatedNotification();
    }

    /**
     * Create an instance of {@link AggregatedResponse }
     * 
     */
    public AggregatedResponse createAggregatedResponse() {
        return new AggregatedResponse();
    }

    /**
     * Create an instance of {@link Swr }
     * 
     */
    public Swr createSwr() {
        return new Swr();
    }

    /**
     * Create an instance of {@link ActionStatus }
     * 
     */
    public ActionStatus createActionStatus() {
        return new ActionStatus();
    }

    /**
     * Create an instance of {@link FwrA }
     * 
     */
    public FwrA createFwrA() {
        return new FwrA();
    }

    /**
     * Create an instance of {@link Dvc }
     * 
     */
    public Dvc createDvc() {
        return new Dvc();
    }

    /**
     * Create an instance of {@link Rqp }
     * 
     */
    public Rqp createRqp() {
        return new Rqp();
    }

    /**
     * Create an instance of {@link PrimitiveContent }
     * 
     */
    public PrimitiveContent createPrimitiveContent() {
        return new PrimitiveContent();
    }

    /**
     * Create an instance of {@link ResponseTypeInfo }
     * 
     */
    public ResponseTypeInfo createResponseTypeInfo() {
        return new ResponseTypeInfo();
    }

    /**
     * Create an instance of {@link FilterCriteria }
     * 
     */
    public FilterCriteria createFilterCriteria() {
        return new FilterCriteria();
    }

    /**
     * Create an instance of {@link Bat }
     * 
     */
    public Bat createBat() {
        return new Bat();
    }

    /**
     * Create an instance of {@link Dvi }
     * 
     */
    public Dvi createDvi() {
        return new Dvi();
    }

    /**
     * Create an instance of {@link SchA }
     * 
     */
    public SchA createSchA() {
        return new SchA();
    }

    /**
     * Create an instance of {@link AnnouncedSubordinateResource }
     * 
     */
    public AnnouncedSubordinateResource createAnnouncedSubordinateResource() {
        return new AnnouncedSubordinateResource();
    }

    /**
     * Create an instance of {@link AeA }
     * 
     */
    public AeA createAeA() {
        return new AeA();
    }

    /**
     * Create an instance of {@link CntA }
     * 
     */
    public CntA createCntA() {
        return new CntA();
    }

    /**
     * Create an instance of {@link CinA }
     * 
     */
    public CinA createCinA() {
        return new CinA();
    }

    /**
     * Create an instance of {@link GrpA }
     * 
     */
    public GrpA createGrpA() {
        return new GrpA();
    }

    /**
     * Create an instance of {@link AcpA }
     * 
     */
    public AcpA createAcpA() {
        return new AcpA();
    }

    /**
     * Create an instance of {@link org.opendaylight.iotdm.primitive.Req }
     * 
     */
    public org.opendaylight.iotdm.primitive.Req createReq() {
        return new org.opendaylight.iotdm.primitive.Req();
    }

    /**
     * Create an instance of {@link MetaInformation }
     * 
     */
    public MetaInformation createMetaInformation() {
        return new MetaInformation();
    }

    /**
     * Create an instance of {@link OperationResult }
     * 
     */
    public OperationResult createOperationResult() {
        return new OperationResult();
    }

    /**
     * Create an instance of {@link Ae }
     * 
     */
    public Ae createAe() {
        return new Ae();
    }

    /**
     * Create an instance of {@link DviA }
     * 
     */
    public DviA createDviA() {
        return new DviA();
    }

    /**
     * Create an instance of {@link Mssp }
     * 
     */
    public Mssp createMssp() {
        return new Mssp();
    }

    /**
     * Create an instance of {@link Svsn }
     * 
     */
    public Svsn createSvsn() {
        return new Svsn();
    }

    /**
     * Create an instance of {@link Stcg }
     * 
     */
    public Stcg createStcg() {
        return new Stcg();
    }

    /**
     * Create an instance of {@link Evcg }
     * 
     */
    public Evcg createEvcg() {
        return new Evcg();
    }

    /**
     * Create an instance of {@link LcpA }
     * 
     */
    public LcpA createLcpA() {
        return new LcpA();
    }

    /**
     * Create an instance of {@link Stcl }
     * 
     */
    public Stcl createStcl() {
        return new Stcl();
    }

    /**
     * Create an instance of {@link Rbo }
     * 
     */
    public Rbo createRbo() {
        return new Rbo();
    }

    /**
     * Create an instance of {@link MemA }
     * 
     */
    public MemA createMemA() {
        return new MemA();
    }

    /**
     * Create an instance of {@link Fwr }
     * 
     */
    public Fwr createFwr() {
        return new Fwr();
    }

    /**
     * Create an instance of {@link Cmdf }
     * 
     */
    public Cmdf createCmdf() {
        return new Cmdf();
    }

    /**
     * Create an instance of {@link Nod }
     * 
     */
    public Nod createNod() {
        return new Nod();
    }

    /**
     * Create an instance of {@link Mem }
     * 
     */
    public Mem createMem() {
        return new Mem();
    }

    /**
     * Create an instance of {@link Ani }
     * 
     */
    public Ani createAni() {
        return new Ani();
    }

    /**
     * Create an instance of {@link Andi }
     * 
     */
    public Andi createAndi() {
        return new Andi();
    }

    /**
     * Create an instance of {@link Evl }
     * 
     */
    public Evl createEvl() {
        return new Evl();
    }

    /**
     * Create an instance of {@link Cmp }
     * 
     */
    public Cmp createCmp() {
        return new Cmp();
    }

    /**
     * Create an instance of {@link Acmp }
     * 
     */
    public Acmp createAcmp() {
        return new Acmp();
    }

    /**
     * Create an instance of {@link Cml }
     * 
     */
    public Cml createCml() {
        return new Cml();
    }

    /**
     * Create an instance of {@link SwrA }
     * 
     */
    public SwrA createSwrA() {
        return new SwrA();
    }

    /**
     * Create an instance of {@link AniA }
     * 
     */
    public AniA createAniA() {
        return new AniA();
    }

    /**
     * Create an instance of {@link Asar }
     * 
     */
    public Asar createAsar() {
        return new Asar();
    }

    /**
     * Create an instance of {@link Rsp }
     * 
     */
    public Rsp createRsp() {
        return new Rsp();
    }

    /**
     * Create an instance of {@link CsrA }
     * 
     */
    public CsrA createCsrA() {
        return new CsrA();
    }

    /**
     * Create an instance of {@link NodA }
     * 
     */
    public NodA createNodA() {
        return new NodA();
    }

    /**
     * Create an instance of {@link BatA }
     * 
     */
    public BatA createBatA() {
        return new BatA();
    }

    /**
     * Create an instance of {@link DvcA }
     * 
     */
    public DvcA createDvcA() {
        return new DvcA();
    }

    /**
     * Create an instance of {@link RboA }
     * 
     */
    public RboA createRboA() {
        return new RboA();
    }

    /**
     * Create an instance of {@link EvlA }
     * 
     */
    public EvlA createEvlA() {
        return new EvlA();
    }

    /**
     * Create an instance of {@link Cmdv }
     * 
     */
    public Cmdv createCmdv() {
        return new Cmdv();
    }

    /**
     * Create an instance of {@link ResourceWrapper }
     * 
     */
    public ResourceWrapper createResourceWrapper() {
        return new ResourceWrapper();
    }

    /**
     * Create an instance of {@link Lcp }
     * 
     */
    public Lcp createLcp() {
        return new Lcp();
    }

    /**
     * Create an instance of {@link Cmpv }
     * 
     */
    public Cmpv createCmpv() {
        return new Cmpv();
    }

    /**
     * Create an instance of {@link Cb }
     * 
     */
    public Cb createCb() {
        return new Cb();
    }

    /**
     * Create an instance of {@link Dlv }
     * 
     */
    public Dlv createDlv() {
        return new Dlv();
    }

    /**
     * Create an instance of {@link DeliveryMetaData }
     * 
     */
    public DeliveryMetaData createDeliveryMetaData() {
        return new DeliveryMetaData();
    }

    /**
     * Create an instance of {@link Cmwr }
     * 
     */
    public Cmwr createCmwr() {
        return new Cmwr();
    }

    /**
     * Create an instance of {@link RebootArgsType }
     * 
     */
    public RebootArgsType createRebootArgsType() {
        return new RebootArgsType();
    }

    /**
     * Create an instance of {@link SoftwareUninstallArgsType }
     * 
     */
    public SoftwareUninstallArgsType createSoftwareUninstallArgsType() {
        return new SoftwareUninstallArgsType();
    }

    /**
     * Create an instance of {@link SoftwareUpdateArgsType }
     * 
     */
    public SoftwareUpdateArgsType createSoftwareUpdateArgsType() {
        return new SoftwareUpdateArgsType();
    }

    /**
     * Create an instance of {@link SoftwareInstallArgsType }
     * 
     */
    public SoftwareInstallArgsType createSoftwareInstallArgsType() {
        return new SoftwareInstallArgsType();
    }

    /**
     * Create an instance of {@link ResetArgsType }
     * 
     */
    public ResetArgsType createResetArgsType() {
        return new ResetArgsType();
    }

    /**
     * Create an instance of {@link LocationRegion }
     * 
     */
    public LocationRegion createLocationRegion() {
        return new LocationRegion();
    }

    /**
     * Create an instance of {@link Attribute }
     * 
     */
    public Attribute createAttribute() {
        return new Attribute();
    }

    /**
     * Create an instance of {@link AnyArgType }
     * 
     */
    public AnyArgType createAnyArgType() {
        return new AnyArgType();
    }

    /**
     * Create an instance of {@link DownloadArgsType }
     * 
     */
    public DownloadArgsType createDownloadArgsType() {
        return new DownloadArgsType();
    }

    /**
     * Create an instance of {@link UploadArgsType }
     * 
     */
    public UploadArgsType createUploadArgsType() {
        return new UploadArgsType();
    }

    /**
     * Create an instance of {@link AccessControlRule.Acco.Acip }
     * 
     */
    public AccessControlRule.Acco.Acip createAccessControlRuleAccoAcip() {
        return new AccessControlRule.Acco.Acip();
    }

    /**
     * Create an instance of {@link AggregatedRequest.Req }
     * 
     */
    public AggregatedRequest.Req createAggregatedRequestReq() {
        return new AggregatedRequest.Req();
    }

    /**
     * Create an instance of {@link Notification.Nev.Om }
     * 
     */
    public Notification.Nev.Om createNotificationNevOm() {
        return new Notification.Nev.Om();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Notification }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "sgn")
    public JAXBElement<Notification> createSgn(Notification value) {
        return new JAXBElement<Notification>(_Sgn_QNAME, Notification.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AggregatedNotification }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "agn")
    public JAXBElement<AggregatedNotification> createAgn(AggregatedNotification value) {
        return new JAXBElement<AggregatedNotification>(_Agn_QNAME, AggregatedNotification.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AggregatedResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "agr")
    public JAXBElement<AggregatedResponse> createAgr(AggregatedResponse value) {
        return new JAXBElement<AggregatedResponse>(_Agr_QNAME, AggregatedResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "atrl")
    public JAXBElement<AttributeList> createAtrl(AttributeList value) {
        return new JAXBElement<AttributeList>(_Atrl_QNAME, AttributeList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link List }{@code <}{@link String }{@code >}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "uril")
    public JAXBElement<List<String>> createUril(List<String> value) {
        return new JAXBElement<List<String>>(_Uril_QNAME, ((Class) List.class), null, ((List<String> ) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResourceWrapper }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.onem2m.org/xml/protocols", name = "rce")
    public JAXBElement<ResourceWrapper> createRce(ResourceWrapper value) {
        return new JAXBElement<ResourceWrapper>(_Rce_QNAME, ResourceWrapper.class, null, value);
    }

}
