//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.21 at 02:34:26 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.onem2m.org/xml/protocols")
package org.opendaylight.iotdm.primitive;
