//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.19 at 11:59:33 PM EDT 
//


package org.opendaylight.iotdm.primitive;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.onem2m.org/xml/protocols}regularResource">
 *       &lt;sequence>
 *         &lt;element name="cr" type="{http://www.onem2m.org/xml/protocols}ID"/>
 *         &lt;element name="sci" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cei" type="{http://www.onem2m.org/xml/protocols}ID"/>
 *         &lt;element name="cdi" type="{http://www.onem2m.org/xml/protocols}ID"/>
 *         &lt;element name="srs" type="{http://www.onem2m.org/xml/protocols}statsRuleStatusType"/>
 *         &lt;element name="sm" type="{http://www.onem2m.org/xml/protocols}statModelType"/>
 *         &lt;element name="cp" type="{http://www.onem2m.org/xml/protocols}scheduleEntries" minOccurs="0"/>
 *         &lt;element name="evi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="ch" type="{http://www.onem2m.org/xml/protocols}childResourceRef" maxOccurs="unbounded"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}sub" maxOccurs="unbounded"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cr",
    "sci",
    "cei",
    "cdi",
    "srs",
    "sm",
    "cp",
    "evi",
    "ch",
    "sub"
})
@XmlRootElement(name = "stcl")
public class Stcl
    extends RegularResource
{

    @XmlElement(required = true)
    protected String cr;
    @XmlElement(required = true)
    protected String sci;
    @XmlElement(required = true)
    protected String cei;
    @XmlElement(required = true)
    protected String cdi;
    @XmlElement(required = true)
    protected BigInteger srs;
    @XmlElement(required = true)
    protected BigInteger sm;
    protected ScheduleEntries cp;
    protected String evi;
    protected List<ChildResourceRef> ch;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected List<Sub> sub;

    /**
     * Gets the value of the cr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCr() {
        return cr;
    }

    /**
     * Sets the value of the cr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCr(String value) {
        this.cr = value;
    }

    /**
     * Gets the value of the sci property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSci() {
        return sci;
    }

    /**
     * Sets the value of the sci property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSci(String value) {
        this.sci = value;
    }

    /**
     * Gets the value of the cei property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCei() {
        return cei;
    }

    /**
     * Sets the value of the cei property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCei(String value) {
        this.cei = value;
    }

    /**
     * Gets the value of the cdi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdi() {
        return cdi;
    }

    /**
     * Sets the value of the cdi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdi(String value) {
        this.cdi = value;
    }

    /**
     * Gets the value of the srs property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSrs() {
        return srs;
    }

    /**
     * Sets the value of the srs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSrs(BigInteger value) {
        this.srs = value;
    }

    /**
     * Gets the value of the sm property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSm() {
        return sm;
    }

    /**
     * Sets the value of the sm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSm(BigInteger value) {
        this.sm = value;
    }

    /**
     * Gets the value of the cp property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduleEntries }
     *     
     */
    public ScheduleEntries getCp() {
        return cp;
    }

    /**
     * Sets the value of the cp property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduleEntries }
     *     
     */
    public void setCp(ScheduleEntries value) {
        this.cp = value;
    }

    /**
     * Gets the value of the evi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEvi() {
        return evi;
    }

    /**
     * Sets the value of the evi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEvi(String value) {
        this.evi = value;
    }

    /**
     * Gets the value of the ch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCh().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ChildResourceRef }
     * 
     * 
     */
    public List<ChildResourceRef> getCh() {
        if (ch == null) {
            ch = new ArrayList<ChildResourceRef>();
        }
        return this.ch;
    }

    /**
     * Gets the value of the sub property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sub property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSub().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Sub }
     * 
     * 
     */
    public List<Sub> getSub() {
        if (sub == null) {
            sub = new ArrayList<Sub>();
        }
        return this.sub;
    }

}
