//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.24 at 05:38:13 PM EDT 
//


package org.opendaylight.iotdm.primitive;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.onem2m.org/xml/protocols}regularResource">
 *       &lt;sequence>
 *         &lt;element name="enc" type="{http://www.onem2m.org/xml/protocols}eventNotificationCriteria" minOccurs="0"/>
 *         &lt;element name="exc" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *         &lt;element name="nu" type="{http://www.onem2m.org/xml/protocols}listOfURIs"/>
 *         &lt;element name="gpi" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="nfu" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="bn" type="{http://www.onem2m.org/xml/protocols}batchNotify" minOccurs="0"/>
 *         &lt;element name="rl" type="{http://www.onem2m.org/xml/protocols}rateLimit" minOccurs="0"/>
 *         &lt;element name="psn" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *         &lt;element name="pn" type="{http://www.onem2m.org/xml/protocols}pendingNotification" minOccurs="0"/>
 *         &lt;element name="nsp" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *         &lt;element name="ln" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="nct" type="{http://www.onem2m.org/xml/protocols}notificationContentType"/>
 *         &lt;element name="nec" type="{http://www.onem2m.org/xml/protocols}eventCat" minOccurs="0"/>
 *         &lt;element name="cr" type="{http://www.onem2m.org/xml/protocols}ID" minOccurs="0"/>
 *         &lt;element name="su" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="ch" type="{http://www.onem2m.org/xml/protocols}childResourceRef"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}sch"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "enc",
    "exc",
    "nu",
    "gpi",
    "nfu",
    "bn",
    "rl",
    "psn",
    "pn",
    "nsp",
    "ln",
    "nct",
    "nec",
    "cr",
    "su",
    "ch",
    "sch"
})
@XmlRootElement(name = "sub")
public class Sub
    extends RegularResource
{

    protected EventNotificationCriteria enc;
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger exc;
    @XmlList
    @XmlElement(required = true)
    protected List<String> nu;
    @XmlSchemaType(name = "anyURI")
    protected String gpi;
    @XmlSchemaType(name = "anyURI")
    protected String nfu;
    protected BatchNotify bn;
    protected RateLimit rl;
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger psn;
    protected BigInteger pn;
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger nsp;
    protected Boolean ln;
    @XmlElement(required = true)
    protected BigInteger nct;
    protected String nec;
    protected String cr;
    @XmlSchemaType(name = "anyURI")
    protected String su;
    protected ChildResourceRef ch;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected Sch sch;

    /**
     * Gets the value of the enc property.
     * 
     * @return
     *     possible object is
     *     {@link EventNotificationCriteria }
     *     
     */
    public EventNotificationCriteria getEnc() {
        return enc;
    }

    /**
     * Sets the value of the enc property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventNotificationCriteria }
     *     
     */
    public void setEnc(EventNotificationCriteria value) {
        this.enc = value;
    }

    /**
     * Gets the value of the exc property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getExc() {
        return exc;
    }

    /**
     * Sets the value of the exc property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setExc(BigInteger value) {
        this.exc = value;
    }

    /**
     * Gets the value of the nu property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nu property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNu().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNu() {
        if (nu == null) {
            nu = new ArrayList<String>();
        }
        return this.nu;
    }

    /**
     * Gets the value of the gpi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGpi() {
        return gpi;
    }

    /**
     * Sets the value of the gpi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGpi(String value) {
        this.gpi = value;
    }

    /**
     * Gets the value of the nfu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNfu() {
        return nfu;
    }

    /**
     * Sets the value of the nfu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNfu(String value) {
        this.nfu = value;
    }

    /**
     * Gets the value of the bn property.
     * 
     * @return
     *     possible object is
     *     {@link BatchNotify }
     *     
     */
    public BatchNotify getBn() {
        return bn;
    }

    /**
     * Sets the value of the bn property.
     * 
     * @param value
     *     allowed object is
     *     {@link BatchNotify }
     *     
     */
    public void setBn(BatchNotify value) {
        this.bn = value;
    }

    /**
     * Gets the value of the rl property.
     * 
     * @return
     *     possible object is
     *     {@link RateLimit }
     *     
     */
    public RateLimit getRl() {
        return rl;
    }

    /**
     * Sets the value of the rl property.
     * 
     * @param value
     *     allowed object is
     *     {@link RateLimit }
     *     
     */
    public void setRl(RateLimit value) {
        this.rl = value;
    }

    /**
     * Gets the value of the psn property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPsn() {
        return psn;
    }

    /**
     * Sets the value of the psn property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPsn(BigInteger value) {
        this.psn = value;
    }

    /**
     * Gets the value of the pn property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPn() {
        return pn;
    }

    /**
     * Sets the value of the pn property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPn(BigInteger value) {
        this.pn = value;
    }

    /**
     * Gets the value of the nsp property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNsp() {
        return nsp;
    }

    /**
     * Sets the value of the nsp property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNsp(BigInteger value) {
        this.nsp = value;
    }

    /**
     * Gets the value of the ln property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLn() {
        return ln;
    }

    /**
     * Sets the value of the ln property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLn(Boolean value) {
        this.ln = value;
    }

    /**
     * Gets the value of the nct property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNct() {
        return nct;
    }

    /**
     * Sets the value of the nct property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNct(BigInteger value) {
        this.nct = value;
    }

    /**
     * Gets the value of the nec property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNec() {
        return nec;
    }

    /**
     * Sets the value of the nec property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNec(String value) {
        this.nec = value;
    }

    /**
     * Gets the value of the cr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCr() {
        return cr;
    }

    /**
     * Sets the value of the cr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCr(String value) {
        this.cr = value;
    }

    /**
     * Gets the value of the su property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSu() {
        return su;
    }

    /**
     * Sets the value of the su property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSu(String value) {
        this.su = value;
    }

    /**
     * Gets the value of the ch property.
     * 
     * @return
     *     possible object is
     *     {@link ChildResourceRef }
     *     
     */
    public ChildResourceRef getCh() {
        return ch;
    }

    /**
     * Sets the value of the ch property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChildResourceRef }
     *     
     */
    public void setCh(ChildResourceRef value) {
        this.ch = value;
    }

    /**
     * Gets the value of the sch property.
     * 
     * @return
     *     possible object is
     *     {@link Sch }
     *     
     */
    public Sch getSch() {
        return sch;
    }

    /**
     * Sets the value of the sch property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sch }
     *     
     */
    public void setSch(Sch value) {
        this.sch = value;
    }

}
